### ISSUE TITLE
Add "Getting started with Jupyter, conda, Python" doc

### ISSUE THREAD

**Issue by leewujung** [uw-echospace/group_docs#2]
@emiliom : The compilation you put together is awesome! Could you make a copy (I guess a "fork" wouldn't work for just one file) here? Thanks!

**Comment by emiliom** [comment]
Done. https://github.com/uw-echospace/group_docs/blob/main/conda_jupyterlab.md

**Comment by leewujung** [comment]
Fantastic! Thank you!

**Comment by leewujung** [comment]
Oops I meant to say could you please add something to the README so people know where it is.

**Comment by emiliom** [comment]
Done.

**Comment by leewujung** [comment]
Thanks!
